# -*- coding: utf-8 -*-
"""2-й слой нейронной сети. Функция потерь для двумерной области. Методология научных исследований.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MP7GKdo5edMddXUvNauC2Q8MRLhnqpfv
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

#from my_optimizer import optimizer_step

from matplotlib import pyplot as plt
from matplotlib import pyplot, cm
from mpl_toolkits.mplot3d import Axes3D

# print("CUDA GPU:", torch.cuda.is_available())
# if torch.cuda.is_available():
#    x = torch.ones(20)
#    print(x.device)
#    x = x.to("cuda:0")
#    # or x=x.to("cuda")
# print(x)
# print(x.device)

def f(x):
    return 0.


from convection_basic import linear_convection_solve

c = 1.0
Lx = 1.0

nx = 40
ny = 5
Lt = ny*0.025


u,u2D = linear_convection_solve(c,Lx,nx+1,Lt,ny)

dx = Lx / nx
dy = Lt / ny
x_space = np.linspace(0, Lx, nx)
y_space = np.linspace(0, Lt, ny)


def analytic_solution(x):
    ix = int(np.where(x_space == x[0])[0])
    iy = int(np.where(y_space == x[1])[0])
    ansol = u2D[iy][ix]
    # if not isinstance(t,np.float64):
    #     qq = 0
    return ansol
# def analytic_solution(x):
#     sol =  (1 / (np.exp(np.pi) - np.exp(-np.pi))) * \
#            np.sin(np.pi * x[0]) * (np.exp(np.pi * x[1]) - np.exp(-np.pi * x[1]))
#     return sol

from torch.autograd.functional import jacobian
from torch.autograd.functional import hessian
from torch.autograd import grad

def loss_function(x, y,pde,psy_trial,f):
    loss_sum = 0.

    for xi in x:
        for yi in y:
            input_point = torch.Tensor([xi, yi])
            input_point.requires_grad_()

            net_out = pde.forward(input_point)
            net_out_w = grad(outputs=net_out, inputs=pde.fc1.weight, grad_outputs=torch.ones_like(net_out),
                       retain_graph=True,create_graph=True)


            net_out_jacobian = jacobian(pde.forward,input_point,create_graph=True)
            # jac1  = get_jacobian(pde.forward,input_point,2)
            net_out_hessian = hessian(pde.forward,input_point,create_graph=True)
            psy_t = psy_trial(input_point, net_out)

            inputs = (input_point, net_out)
            psy_t_jacobian = jacobian(psy_trial, inputs,create_graph=True)[0]
            psy_t_hessian  = hessian(psy_trial,inputs,create_graph=True)
            psy_t_hessian = psy_t_hessian[0][0]
            # acobian(jacobian(psy_trial))(input_point, net_out

            gradient_of_trial_d2x = psy_t_hessian[0][0]
            gradient_of_trial_d2y = psy_t_hessian[1][1]

            # D_gradient_of_trial_d2x_D_W0 = grad(outputs=gradient_of_trial_d2x, inputs=pde.fc1.weight, grad_outputs=torch.ones_like(gradient_of_trial_d2x), retain_graph=True)
            # D_gradient_of_trial_d2y_D_W0 = grad(outputs=gradient_of_trial_d2y, inputs=pde.fc1.weight, grad_outputs=torch.ones_like(gradient_of_trial_d2y), retain_graph=True)
            # D_func_D_W0 = grad(outputs=func,iputs=pde.fc1.weight,grad_outputs=torch.ones_like(func))
            func = f(input_point)
            func_t = torch.Tensor([func])
            func_t.requires_grad_()

            err_sqr = ((gradient_of_trial_d2x + gradient_of_trial_d2y) - func_t) ** 2
            # D_err_sqr_D_W0 = 2*((gradient_of_trial_d2x + gradient_of_trial_d2y) - func)*(
            #                     (D_gradient_of_trial_d2x_D_W0 + D_gradient_of_trial_d2y_D_W0) -D_func_D_W0
            #                     )

            loss_sum += err_sqr
            qq = 0

    return loss_sum

# from google.colab import drive
# drive.mount('/content/drive')
#
# # Commented out IPython magic to ensure Python compatibility.
# import os
# from glob import glob
# os.chdir("/content/drive/MyDrive/random_weights")
# # %pwd

import numpy as np

# w0 = np.loadtxt('w0.out')
# w1 = np.loadtxt('w1.out')

import torch.nn as nn
# нейронная сеть для решения уравнения Пуассона
class PDEnet(nn.Module):
    def __init__(self,N):
        super(PDEnet,self).__init__()
        self.N = N
        fc1 = nn.Linear(2,self.N) # первый слой
        #fc1.weight = nn.Parameter(torch.from_numpy(w0).T.double())
        # fc1.bias = nn.Parameter(torch.zeros(fc1.bias.shape).double())
        fc2 = nn.Linear(self.N, 1) # второй слой
        #fc2.weight = nn.Parameter(torch.from_numpy(w1).reshape(1,w1.shape[0]).double())
        # fc2.bias = nn.Parameter(torch.zeros(fc2.bias.shape).double())
        self.fc1 = fc1

        self.fc2 = fc2

    def forward(self,x):
        x = x.reshape(1, 2)
        y = self.fc1(x)
        y = torch.sigmoid(y)
        y = self.fc2(y.reshape(1, self.N))
        return y

def A(x):
#    return (x[1] * torch.sin(np.pi * x[0]))
     if x[1] == Lt or x[1] == 0.0 or x[0] == 0.0 or x[0]== Lx:
         return analytic_solution(x)
     else:
         return 0.0


def psy_trial(x, net_out):
    return A(x) + x[0] * (Lx - x[0]) * x[1] * (Lt - x[1]) * net_out

nx = 40
ny = 5
pde = PDEnet(nx)
# dx = 1. / nx
# dy = 1. / ny

x_space = torch.linspace(0, Lx, nx).double()
y_space = torch.linspace(0, Lt, ny).double()
print("CUDA GPU:", torch.cuda.is_available())
if torch.cuda.is_available():
  print(torch.device)
  print(x_space.device)
  x_space.to("cuda:0")
  #y_space.to("cuda:0")
  #print(x_space)
  print(x_space.device)

input_point = torch.zeros(2)#.double()

input_point.shape,pde.fc1.weight.T.shape

pde.fc1.weight.dtype,input_point.dtype,pde.fc1.bias.dtype

torch.matmul(input_point,pde.fc1.weight.T)

out1 = pde.fc1(input_point)
out1

#torch.matmul(out1.reshape(1,3),pde.fc2.weight.reshape(1,3).T)

pde.fc2(out1)

net_out = pde.forward(input_point)
net_out

psy_t = psy_trial(input_point, net_out)
print(psy_t)

loss = loss_function(x_space, y_space,pde,psy_trial,f)
loss.backward()
print(x_space.grad)

lmb = 0.001
optimizer = torch.optim.SGD(pde.parameters(), lr=lmb)
import time
t1 = time.time()
for i in range(100):
    #print('begin ',i,loss.item())
    optimizer.zero_grad()
    #print('zero grad ',i,loss.item())
    #print(x_space.device,y_space.device)
    loss = loss_function(x_space, y_space,pde,psy_trial,f)
    #print(loss.device)
    print(i,loss.item())
    loss.backward(retain_graph=True)
    #print('loop end ',i,loss.item())
    optimizer.step()

    print('step ',i,loss.item())
t2 = time.time()
print('computation time ',t2-t1)

surface = np.zeros((nx,ny))
an_surface = np.zeros((nx,ny))
for i, x in enumerate(x_space):
    for j, y in enumerate(y_space):
        input_point = torch.Tensor([x, y])
        input_point.requires_grad_()
        net_out = pde.forward(input_point)

        psy_t = psy_trial(input_point, net_out)
        surface[i][j] = psy_t
        an_surface[i][j] = analytic_solution([x, y])
diff = np.max(np.abs(surface-an_surface))
print(diff)

import matplotlib.pyplot as plt
import numpy as np
# fig = plt.figure()
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
X, Y = np.meshgrid(x_space.numpy(), y_space.numpy())
surf = ax.plot_surface(X, Y, surface.T, rstride=1, cstride=1, cmap=cm.viridis,
                       linewidth=0, antialiased=False)
plt.title('Neural solution')
plt.savefig('neural.png')

fig = plt.figure()
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
X, Y = np.meshgrid(x_space.numpy(), y_space.numpy())
surf = ax.plot_surface(X, Y, an_surface.T, rstride=1, cstride=1, cmap=cm.viridis,
                       linewidth=0, antialiased=False)
plt.title('Analytic solution')
plt.savefig('analytic.png')

from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(an_surface, surface)
print(mape)

import numpy as np
diff = np.abs(an_surface-surface)
md = np.max(diff)
md

np.where(diff == md)

print(surface[5][7],an_surface[5][7],np.abs(surface[5][7]-an_surface[5][7]),np.abs(surface[5][7]-an_surface[5][7])/np.abs(an_surface[5][7]))